name: Build React app

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/test-zigzag-react-web
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm i
      - name: Build
        run: CI=false npm run build --if-present