name: Build Solution

on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/TestZigzagApi
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'
      - name: Setup Node.js 16.x
          uses: actions/setup-node@v1
            with:
              node-version: '16.x'
      - name: Install dependencies .NET
        run: dotnet restore
      - name: Build .NET
        run: dotnet build --configuration Release --no-restore
      - name: Install dependencies react
        run: npm i
      - name: Build react
        run: CI=false npm run build --if-present