name: Build Solution

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/TestZigzagApi
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

    build-react:
      runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./src/test-zigzag-react-web
        steps:
          - uses: actions/checkout@v3
          - name: Setup Node.js 16.x
            uses: actions/setup-node@v1
            with:
              node-version: '16.x'
          - name: Install dependencies
            run: npm i
          - name: Build
            run: CI=false npm run build --if-present